### ISSUE TITLE
4.9 Kernel 의 evdev 드라이버 업데이트 적용 필요 (X 에서의 마우스, 키보드 문제 관련)

### ISSUE THREAD

**Issue by jollaman999** [hcloud-classic/hcloudclassic-kernel#11]
* 일부 Debian 9 기반의 4.9 Kernel 을 사용하는 배포판 들에서 X 가 시작되고서 마우스와 키보드를 사용하려고 하면 동작하지 않거나, 마우스의 드래그 동작이 작동하지 않는 문제가 있음.
    * antiX 17.4.1 (Debian 9 기반, 4.9 Kernel 사용)
        * slim 데스크탑 매니저 시작 후 키보드, 마우스 동작하지 않음
    * LMDE 3 (Debian 9 기반, 4.9 Kernel 사용)
        * 마우스, 키보드 동작하나 마우스의 드래그 동작이 작동하지 않음.
* 문제의 원인은 X 에서 Kernel 로 마우스, 키보드, 터치스크린등 input 동작들을 전달해주는 edev 드라이버의 문제로 파악됨,

**Comment by niconicodex** [comment]
* 4.9 Kernel 의 evdev 드라이버 관련 변경 사항들 적용 후 마우스, 키보드 정상 동작 가능!!
* edev 드라이버 관련 커밋 적용
https://github.com/hcloud-classic/hcloudclassic-kernel/blob/master/linux-2.6.32/drivers/input/evdev.c
