### ISSUE TITLE
elogind 같은 systemd 기반의 데몬에서의 cgroup 적용 방지

### ISSUE THREAD

**Issue by jollaman999** [hcloud-classic/hcloudclassic-kernel#12]
- cgroup 이 활성화 되면 DISTANT_FORK 가 동작하지 않음.

**Comment by niconicodex** [comment]
* elogind, systemd 기반 데몬이 구동될시 cgroup 을 사용하지 않도록 수정
https://github.com/hcloud-classic/hcloudclassic-kernel/blob/master/linux-2.6.32/kernel/cgroup.c#L2097
https://github.com/hcloud-classic/hcloudclassic-kernel/blob/master/linux-2.6.32/kernel/cgroup.c#L2105

close #12

**Comment by niconicodex** [comment]
* elogind, systemd 기반 데몬이 구동될시 cgroup 을 사용하지 않도록 수정
https://github.com/hcloud-classic/hcloudclassic-kernel/blob/master/linux-2.6.32/kernel/cgroup.c#L2097
https://github.com/hcloud-classic/hcloudclassic-kernel/blob/master/linux-2.6.32/kernel/cgroup.c#L2105
close #12
